'use strict';

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { readUpload, detectKind } = require('../src/files');
const { FileReadError } = require('../src/files/errors');
const { parseIcs } = require('../src/files/ics');
const { assertReasonableZip } = require('../src/files/spreadsheet');
const { FIXTURES, silentLogger } = require('./helpers');

// Fixtures are generated by `npm run fixtures` for a semester that starts on 2026-08-31.

function upload(name, buffer = fs.readFileSync(path.join(FIXTURES, name))) {
  return readUpload({ originalname: name, buffer }, { logger: silentLogger });
}

async function rejects(promise, pattern) {
  await assert.rejects(promise, (err) => err instanceof FileReadError && pattern.test(err.message));
}

describe('file type detection', () => {
  it('classifies uploads by extension, case-insensitively', () => {
    assert.equal(detectKind('Syllabus.PDF'), 'pdf');
    assert.equal(detectKind('schedule.csv'), 'csv');
    assert.equal(detectKind('schedule.xlsx'), 'xlsx');
    assert.equal(detectKind('calendar.ics'), 'ics');
    assert.equal(detectKind('photo.jpeg'), 'image');
    assert.equal(detectKind('notes.docx'), null);
    assert.equal(detectKind('old.xls'), null);
  });

  it('explains unsupported files, with a hint for legacy .xls', async () => {
    await rejects(upload('notes.docx', Buffer.from('PK')), /unsupported file type/);
    await rejects(upload('grades.xls', Buffer.from('x')), /legacy \.xls files aren't supported/);
  });
});

describe('PDF', () => {
  it('extracts the text layer', async () => {
    const doc = await upload('astr-1270-syllabus.pdf');
    assert.equal(doc.kind, 'pdf');
    assert.equal(doc.file, undefined);
    assert.match(doc.text, /ASTR 1270: Introduction to Planetary Science/);
    assert.match(doc.text, /Wed, Sep 9\s+Reading Quiz 1\s+Start of class/);
    assert.match(doc.text, /Midterm Exam/);
    assert.match(doc.text, /No class: campus holiday/);
  });

  it('sends scanned PDFs (no text layer) to the model as a file', async () => {
    const doc = await upload('scanned-syllabus.pdf');
    assert.equal(doc.text, undefined);
    assert.equal(doc.file.mime, 'application/pdf');
    assert.ok(Buffer.from(doc.file.base64, 'base64').subarray(0, 5).equals(Buffer.from('%PDF-')));
  });

  it('rejects files that are not PDFs', async () => {
    await rejects(upload('fake.pdf', Buffer.from('<html>not a pdf</html>')), /doesn't look like a valid PDF/);
  });
});

describe('CSV', () => {
  it('turns rows into a pipe-separated table', async () => {
    const doc = await upload('stat-2380-schedule.csv');
    assert.equal(doc.kind, 'csv');
    const lines = doc.text.split('\n');
    assert.equal(lines[0], 'STAT 2380 Applied Statistics with R: Fall 2026 schedule');
    assert.equal(lines[1], 'Week | Date | Topic | Deliverable | Due');
    assert.ok(lines.includes('2 | 9/8/2026 | Visualizing distributions | Homework 1 | 11:59 PM'));
    assert.ok(lines.includes('1 | 9/1/2026 | Course overview; R and RStudio setup'), 'trailing empty cells are trimmed');
  });

  it('handles quoted fields, a BOM and Windows line endings', async () => {
    const csv = '\uFEFFDate,Item,Notes\r\n2026-09-01,"Essay 1, draft","Bring ""two"" copies"\r\n';
    const doc = await upload('quoted.csv', Buffer.from(csv));
    assert.equal(doc.text, 'Date | Item | Notes\n2026-09-01 | Essay 1, draft | Bring "two" copies');
  });

  it('rejects empty and binary files', async () => {
    await rejects(upload('empty.csv', Buffer.from('\n\n')), /appears to be empty/);
    await rejects(upload('binary.csv', Buffer.from([0x41, 0x00, 0x42])), /binary file/);
  });
});

describe('XLSX', () => {
  it('reads cells, formatting date cells as YYYY-MM-DD', async () => {
    const doc = await upload('stat-2380-schedule.xlsx');
    assert.equal(doc.kind, 'xlsx');
    const lines = doc.text.split('\n');
    assert.equal(lines[0], '[Sheet: Schedule]');
    assert.equal(lines[1], 'STAT 2380 Applied Statistics with R: Fall 2026 schedule');
    assert.ok(lines.includes('Week | Date | Topic | Deliverable | Due'));
    assert.ok(lines.includes('2 | 2026-09-08 | Visualizing distributions | Homework 1 | 11:59 PM'));
    assert.ok(lines.includes('8 | 2026-10-22 | Midterm exam (in class) | Midterm Exam | 1:00 PM'));
  });

  it('refuses archives that are not spreadsheets or would decompress to something huge', async () => {
    await rejects(upload('fake.xlsx', Buffer.from('definitely not a zip file')), /valid \.xlsx/);

    const zip = fs.readFileSync(path.join(FIXTURES, 'stat-2380-schedule.xlsx'));
    const forged = Buffer.from(zip);
    const eocd = forged.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06]));
    const firstEntry = forged.readUInt32LE(eocd + 16);
    forged.writeUInt32LE(0xfffffff0, firstEntry + 24); // claim a ~4 GB uncompressed size
    assert.throws(() => assertReasonableZip(forged), /too large once uncompressed/);
  });
});

describe('ICS', () => {
  it('lists events in date order with times, ranges and the calendar name', async () => {
    const doc = await upload('writ-1190-calendar.ics');
    assert.equal(doc.kind, 'ics');
    const lines = doc.text.split('\n');
    assert.equal(lines[0], 'Calendar: WRIT 1190 Writing Seminar: Cities and Memory');
    assert.equal(lines[1], '2026-09-06 23:59 | Discussion Post 1 | Introduce a place you remember well (250 words).');
    assert.ok(lines.includes('2026-10-12 to 2026-10-14 | One-on-one Conference | Sign up for a 20-minute slot.'));
    assert.ok(lines.includes('2026-09-14 | No class: campus holiday'));
    const dates = lines.slice(1).map((line) => line.slice(0, 10));
    assert.deepEqual(dates, [...dates].sort());
  });

  it("converts UTC timestamps to the student's time zone", () => {
    const ics = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'BEGIN:VEVENT',
      'UID:canvas-1',
      'DTSTART:20261006T045900Z',
      'SUMMARY:Essay 1 Draft',
      'END:VEVENT',
      'END:VCALENDAR',
    ].join('\r\n');
    const chicago = parseIcs(ics, { timeZone: 'America/Chicago' }).items[0];
    assert.deepEqual([chicago.date, chicago.time], ['2026-10-05', '23:59']);
    const utc = parseIcs(ics, { timeZone: 'Not/AZone' }).items[0];
    assert.deepEqual([utc.date, utc.time], ['2026-10-06', '04:59']);
  });

  it('expands recurring events, honouring EXDATE and moved occurrences', () => {
    const ics = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'BEGIN:VEVENT',
      'UID:weekly',
      'DTSTART:20260906T235900',
      'RRULE:FREQ=WEEKLY;COUNT=4',
      'EXDATE:20260913T235900',
      'SUMMARY:Reading response',
      'END:VEVENT',
      'BEGIN:VEVENT',
      'UID:weekly',
      'RECURRENCE-ID:20260920T235900',
      'DTSTART:20260921T120000',
      'SUMMARY:Reading response (moved)',
      'END:VEVENT',
      'END:VCALENDAR',
    ].join('\r\n');
    const items = parseIcs(ics).items.map((i) => `${i.date} ${i.time} ${i.summary}`);
    assert.deepEqual(items, [
      '2026-09-06 23:59 Reading response',
      '2026-09-21 12:00 Reading response (moved)',
      '2026-09-27 23:59 Reading response',
    ]);
  });

  it('rejects files that are not calendars or have no events', async () => {
    await rejects(upload('notes.ics', Buffer.from('this is just some text, not a calendar file at all')), /iCalendar/);
    const empty = 'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//x//EN\r\nEND:VCALENDAR\r\n';
    await rejects(upload('empty.ics', Buffer.from(empty)), /contains no events/);
  });
});

describe('text and images', () => {
  it('decodes UTF-8 and UTF-16 text files', async () => {
    const text = 'Essay 1 due Friday, September 18 at 11:59 PM';
    assert.equal((await upload('notes.txt', Buffer.from(text))).text, text);
    const utf16 = Buffer.concat([Buffer.from([0xff, 0xfe]), Buffer.from(text, 'utf16le')]);
    assert.equal((await upload('notes.txt', utf16)).text, text);
  });

  it('checks image signatures', async () => {
    const png = Buffer.concat([Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]), Buffer.alloc(16)]);
    const doc = await upload('photo.png', png);
    assert.equal(doc.file.mime, 'image/png');
    const jpeg = await upload('photo.png', Buffer.from([0xff, 0xd8, 0xff, 0xe0, 0, 0]));
    assert.equal(jpeg.file.mime, 'image/jpeg', 'the content decides, not the extension');
    await rejects(upload('photo.jpg', Buffer.from('<svg></svg>')), /doesn't look like a PNG, JPEG or WEBP/);
  });
});
